const express = require('express')
const router = express.Router()
const dashboardController = require('../controllers/dashboardController')
const { authenticate } = require('../middleware/auth')

router.use(authenticate)

router.get('/dashboard', dashboardController.getDashboard)
router.get('/insights', dashboardController.getAIInsights)
router.get('/goals', dashboardController.getGoals)
router.post('/goals', dashboardController.createGoal)

router.get('/transactions', dashboardController.getTransactions)
router.post('/transactions', dashboardController.addTransaction)

router.post('/expenditures', dashboardController.addDailyExpenditure)
router.get('/expenditures', dashboardController.getDailyExpenditures)

router.get('/autosave/rules', dashboardController.getAutoSaveRules)
router.post('/autosave/rules', dashboardController.createAutoSaveRule)
router.patch('/autosave/rules/:ruleId', dashboardController.toggleAutoSaveRule)

router.get('/nudges', dashboardController.getNudges)
router.patch('/nudges/mark-all-read', dashboardController.markAllNudgesRead)
router.patch('/nudges/:nudgeId/read', dashboardController.readNudge)

router.get('/roundup/status', dashboardController.getRoundUpStatus)
router.post('/roundup/toggle', dashboardController.toggleRoundUp)

router.get('/gamification', dashboardController.getGamificationProfile)
router.get('/groups', dashboardController.listGroups)
router.post('/groups', dashboardController.createSavingsGroup)
router.post('/groups/:groupId/join', dashboardController.joinSavingsGroup)
router.post('/groups/:groupId/commitments', dashboardController.makeCommitment)
router.get('/groups/:groupId/leaderboard', dashboardController.getGroupLeaderboard)
router.get('/groups/:groupId/messages', dashboardController.getGroupMessages)
router.post('/groups/:groupId/messages', dashboardController.sendGroupMessage)
router.get('/groups/:groupId/members', dashboardController.getGroupMembers)

router.get('/quests', dashboardController.getDailyQuests)
router.post('/quests/:questKey/complete', dashboardController.completeQuest)

router.get('/advice', dashboardController.getPersonalisedAdvice)
router.post('/onboarding/segment', dashboardController.upsertOnboardingSegment)
router.get('/resilience/score', dashboardController.getResilienceScore)
router.get('/resilience/runway-breakdown', dashboardController.getRunwayBreakdown)
router.get('/debt/risks', dashboardController.getDebtRisks)

// Actionable interventions
router.post('/cool-down/predict', dashboardController.predictPurchaseImpact)
router.post('/cool-down/add', dashboardController.addToCooldown)
router.get('/cool-down/list', dashboardController.getCooldownList)
router.post('/cool-down/:entryId/confirm', dashboardController.confirmCooldownEntry)
router.post('/cool-down/:entryId/abandon', dashboardController.abandonCooldownEntry)
router.post('/interventions/budget-reset', dashboardController.applyBudgetReset)
router.post('/interventions/adjust-multiplier', dashboardController.adjustRoundUpMultiplier)
router.post('/interventions/auto-budget-reset', dashboardController.tryAutoBudgetReset)
router.post('/interventions/auto-increase-multiplier', dashboardController.tryAutoIncreaseMultiplier)
router.get('/nudges/adaptive', dashboardController.getAdaptiveNudges)
router.post('/interventions/log', dashboardController.logIntervention)
router.patch('/interventions/:logId/status', dashboardController.updateInterventionStatus)
router.get('/interventions/outcomes', dashboardController.getInterventionOutcomes)
router.get('/micro-learning/cards', dashboardController.listMicroLearningCards)
router.post('/micro-learning/cards', dashboardController.createMicroLearningCard)
router.patch('/micro-learning/cards/:cardId/complete', dashboardController.completeMicroLearningCard)
router.get('/commitment-contracts', dashboardController.listCommitmentContracts)
router.get('/commitment-contracts/recommendations', dashboardController.getContractRecommendations)
router.post('/commitment-contracts/recommendations/accept', dashboardController.acceptContractRecommendation)
router.post('/commitment-contracts', dashboardController.createCommitmentContract)
router.patch('/commitment-contracts/:contractId/resolve', dashboardController.resolveCommitmentContract)
router.post('/commitment-contracts/check-expiry', dashboardController.checkExpiringContracts)
router.post('/commitment-contracts/auto-arbitrate', dashboardController.autoArbitrateContracts)
router.post('/commitment-contracts/auto-arbitrate/all', dashboardController.runAutoArbitrationAll)
router.get('/gxbank/integration-story', dashboardController.getGXBankIntegrationStory)

router.post('/ai/chat', dashboardController.aiChat)
router.get('/ai/suggest-budgets', dashboardController.aiSuggestBudgets)
router.post('/ai/action', dashboardController.handleAIAction)
router.get('/badges', dashboardController.getAllBadges)
router.get('/analytics/spending', dashboardController.getSpendingAnalysis)

router.get('/calendar', dashboardController.getCalendarData)
router.get('/calendar/day', dashboardController.getDayDetail)

router.get('/fixed-expenses', dashboardController.getFixedExpenses)
router.post('/fixed-expenses', dashboardController.addFixedExpense)
router.post('/fixed-expenses/record', dashboardController.recordFixedExpenses)
router.delete('/fixed-expenses/:id', dashboardController.deleteFixedExpense)

router.get('/autopilot/status', dashboardController.getAutopilotStatus)
router.post('/autopilot/setup', dashboardController.setupAutopilot)
router.post('/autopilot/quick-enable', dashboardController.quickEnableAutopilot)
router.patch('/autopilot/toggle', dashboardController.toggleAutopilot)
router.get('/autopilot/daily-limit', dashboardController.getDailyLimit)
router.post('/autopilot/record-spending', dashboardController.recordDailySpending)
router.get('/autopilot/piggy-bank', dashboardController.getPiggyBank)
router.post('/autopilot/piggy-bank', dashboardController.addPiggyBankRoundUp)
router.delete('/expenditures/:expenseId', dashboardController.deleteExpenditure)
router.delete('/groups/:groupId/leave', dashboardController.leaveGroup)
router.delete('/goals/:goalId', dashboardController.deleteGoal)
router.delete('/autosave/rules/:ruleId', dashboardController.deleteAutoSaveRule)

// Pet system
router.get('/pet/status', dashboardController.getPetStatus)
router.post('/pet/calculate-ep', dashboardController.calculatePetEP)
router.post('/pet/dismiss-dialogue/:dialogueId', dashboardController.dismissPetDialogue)
router.get('/pet/rewards', dashboardController.getPetRewards)
router.post('/pet/rewards/:rewardId/claim', dashboardController.claimPetReward)
router.get('/pet/history', dashboardController.getPetHistory)

module.exports = router
